[package]
name = "scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
tmdb_client = { version = "1.8.0", features = ["daily-exports"] }
chrono = { version = "0.4.22", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
# postgres = "0.19"
postgres-types = { version = "0.2.12", features = ["with-serde_json-1"] }

openssl = "0.10.41"
# openssl-sys = "0.9.80"
# openssl = { version = "0.10.41", features = ["vendored"] }
postgres-openssl = "0.5.0"
# chrono = "0.4.22"

[dependencies.postgres]
version = "0.19.3"
features = [
    "with-uuid-1",
    "with-chrono-0_4"
]

[dependencies.uuid]
version = "1.1.2"
