name: Run Rust script (daily)

on:
  schedule:
    - cron: "0 12 1/2 * *" # Every two days
    # - cron: "0 0 * * 0" # Every Sunday
  workflow_dispatch:

jobs:
  run-rust-script:
    name: Build and run scripts/main.rs
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      CERT_URL: ${{ secrets.CERT_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Download root.crt for CockroachDB
        run: |
          curl --create-dirs -o $HOME/.postgresql/root.crt '${{ secrets.CERT_URL }}'

      - name: Build `scripts` Cargo project
        working-directory: scripts
        run: |
          cargo build --release

      - name: Run `scripts` Cargo project
        working-directory: scripts
        run: |
          cargo run --release
